<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Virtual_ControlBox" Id="{3bc0b76f-6aa1-4b1e-9442-9f864c25cc0b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Virtual_ControlBox IMPLEMENTS I_ControlBox
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>